services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Model\DataCollectorInterface:
            tags:
                - 'data_collector'

    App\:
        resource: '../src/'
        exclude:
            - '../src/Model/'

    App\Application:
        public: true
